DOMINIOS_CIENCIAS_SOCIALES_ZS = [
    "Estudios relacionados con política, sociología, derecho, antropología o geografía humana",
    "Análisis en economía, administración de empresas, finanzas o contabilidad",
    "Educación y pedagogía",
    "Psicología y ciencias del comportamiento",
    "Historia y estudios culturales",
    "Migración y estudios de población",
    "Servicios sociales y bienestar",
    "Comportamiento social y relaciones humanas",
    "Estudios sobre minorías y diversidad",
    "Derechos humanos",
    "Exilio y refugio",
    "Estudios de género y migración",
    "Demografía y movimientos poblacionales",
    "Sociología de la migración",
    "Política migratoria y legislación internacional",
    "Integración social y cultural de inmigrantes",
    "Crisis humanitarias y desplazamiento forzado",
    "Estudios postcoloniales y movimientos de población",
    "Geografía de la población y flujos migratorios",
    "Economía de la migración",
    "Psicología transcultural",
    "Legislación sobre asilo y refugio",
    "Impacto social y económico de la migración",
    "Salud y migración",
    "Educación intercultural",
    "Discriminación y xenofobia",
    "Identidad y aculturación",
    "Tráfico de personas y trata",
    "Fronteras y seguridad",
    "Globalización y migración",
    "Asilo y refugio",
    "Políticas migratorias",
    "Diásporas y comunidades transnacionales",
    "Desarrollo y migración",
    "Mercado laboral y migración",
    "Migración forzada",
    "Migración circular y retorno",
    "Migración irregular y contrabando",
    "Gobernanza migratoria",
    "Vulnerabilidad y protección de migrantes",
    "Causas y consecuencias de la migración",
    "Migración y desarrollo sostenible",
    "Cambio climático y migración",
    "Movilidad humana internacional"
]

DOMINIOS_TECNICOS_CANDIDATOS_ZS = [
    "Investigaciones en ingeniería civil, geotecnia, geología estructural o geociencias",
    "Temas de salud pública, medicina clínica, biotecnología o biología molecular",
    "Investigación en física teórica, química inorgánica, matemáticas aplicadas o ciencias exactas",
    "Informática y sistemas de información",
    "Ingeniería eléctrica y electrónica",
    "Ciencia de materiales",
    "Inteligencia artificial y robótica"
]

ETIQUETAS_MIGRACION = [
    "MIGRACIONES",
    "MOVILIDAD Y MIGRACIONES INTERIORES",
    "MOVILIDAD Y MIGRACIONES INTERNACIONALES",
    "INMIGRANTE",
    "MIGRACIÓN",
    "INMIGRACIÓN",
    "MIGRANTE",
    "EMIGRACIÓN",
    "POLÍTICA MIGRATORIA",
    "REFUGIADO",
    "REFUGIADOS",
    "ASILO",
    "SOLICITANTE DE ASILO",
    "SOLICITANTES DE ASILO",
    "DESPLAZADO",
    "DESPLAZADOS",
    "DIÁSPORA",
    "DIÁSPORAS",
    "COMUNIDAD MIGRANTE",
    "COMUNIDADES MIGRANTES",
    "INTEGRACIÓN MIGRATORIA",
    "ADAPTACIÓN CULTURAL",
    "COHESIÓN SOCIAL",
    "XENOFOBIA",
    "DISCRIMINACIÓN",
    "REMESAS",
    "TRÁFICO DE PERSONAS",
    "TRATA DE PERSONAS",
    "FRONTERAS",
    "CONTROL FRONTERIZO",
    "MOVILIDAD HUMANA",
    "MIGRACIÓN CIRCULAR",
    "RETORNO",
    "RETORNADOS",
    "IRREGULARIDAD MIGRATORIA",
    "DOCUMENTACIÓN MIGRATORIA",
    "CIUDADANÍA",
    "APATRIDIA",
    "LEY DE EXTRANJERÍA",
    "DERECHO MIGRATORIO",
    "COOPERACIÓN INTERNACIONAL",
    "CRISIS HUMANITARIAS",
    "ACUERDOS MIGRATORIOS",
    "MERCADO LABORAL",
    "CONTRATACIÓN EN ORIGEN",
    "DERECHOS LABORALES",
    "EXPLOTACIÓN LABORAL",
    "SALUD MIGRANTE",
    "EDUCACIÓN DE MIGRANTES",
    "VULNERABILIDAD",
    "PROTECCIÓN INTERNACIONAL",
    "NACIONALIDAD",
    "DOBLE NACIONALIDAD",
    "TRABAJADOR MIGRANTE",
    "TRABAJADORA MIGRANTE",
    "MOVILIDADES",
    "MOVILIDAD TRANSNACIONAL",
    "GÉNERO Y MIGRACIÓN",
    "MENORES NO ACOMPAÑADOS",
    "MIGRACIÓN Y DESARROLLO",
    "POLÍTICAS DE ASILO",
    "POLÍTICAS DE INMIGRACIÓN",
    "CONTROLES MIGRATORIOS",
    "FLUJOS MIGRATORIOS",
    "CORREDORES MIGRATORIOS",
    "CIUDADES REFUGIO",
    "CONVENIOS INTERNACIONALES",
    "POLÍTICAS PÚBLICAS MIGRATORIAS"
]